#!/bin/bash
# Create default chains
iptables -N TCP && echo "Created TCP chain" || exit
iptables -N UDP && echo "Created UDP chain" || exit

# Drop forwards as this is not a router
iptables -P FORWARD DROP && echo "Drop FORWARD packets"

# Allow all outbound rules
iptables -P OUTPUT ACCEPT && echo "Allow OUTPUT packets"

# Input security defaults
iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP
iptables -A INPUT -p icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT
iptables -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
iptables -A INPUT -p tcp --syn -m conntrack --ctstate NEW -j TCP
iptables -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
iptables -A INPUT -p tcp -j REJECT --reject-with tcp-rst
iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable

# Allow certain ports in
# Examples:
# iptables -A TCP -p tcp --dport 80 -j ACCEPT # Allows TCP port 80 (HTTP)
# iptables -A UDP -p udp --dport 53 -j ACCEPT # Allows UDP port 53 (DNS)
# Input rules:
iptables -A TCP -p tcp --dport 80 -j ACCEPT

# Drop non specified input methods
iptables -P INPUT DROP && echo "Drop INPUT packets"
